version: '3.8'

services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: testdb
      PGDATA: /data/postgres
    ports:
      - 5434:5432
    networks:
      - nestjs-network
networks:
    nestjs-network:
    